name: cicd

on:
  push:
    paths:
      - "src/**"
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Shorten commit ID
        id: commit
        shell: bash
        run: echo "commit_id=${GITHUB_SHA::6}" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: slmorrell/python-app:${{ steps.commit.outputs.commit_id }}

    outputs:
      commit_id: ${{ steps.commit.outputs.commit_id }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Modify values file
        shell: bash
        env:
          COMMIT_ID: ${{ needs.ci.outputs.commit_id }}
        run: |
          echo "$COMMIT_ID"
          sed -i -E "s|^([[:space:]]*tag:).*|\1 \"$COMMIT_ID\"|" charts/python-app/values.yaml
          grep -A4 "^image:" charts/python-app/values.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updates values.yaml with commit ${{needs.ci.outputs.commit_id}}"

      - name: Install argocd
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure  \
            --grpc-web \
            --username admin \
            --password  ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app
